from datetime import datetime

print("Welcome to the Grocery List App.")
now = datetime.now()
currentdate_time = now.strftime("%d/%m/%y    %H:%M")
print("Current date & time: ", currentdate_time)
print()
grocery_list = ['Eggs', 'Milk']
print(grocery_list)
print()
print("Type of food to add to the grocery list: ")
grocery_list.append(input().title())
print("Type of food to add to the grocery list: ")
grocery_list.append(input().title())
print("Type of food to add to the grocery list: ")
grocery_list.append(input().title())
print()
print("Simulating geocery shopping...")
print()
print("Current grocery list :" + str(len(grocery_list)) + ' items!')

grocery_list.sort()
print(grocery_list)
print()
print("What food item did you just buy:")
grocery_list.remove(input().title())
print("What food item did you just buy:")
grocery_list.remove(input().title())
print()
print("Current grocery list:" + str(len(grocery_list)) + 'items!')
print(grocery_list)
print()
print("What food item did you just buy:")
grocery_list.remove(input().title())
print()
print("Current grocery list:" + str(len(grocery_list)) + 'items!')
print(grocery_list)
print()
print("Sorry, the store is out os " + str(grocery_list[1]))
grocery_list.pop(1)
print()
print("What food would you like instead:")
grocery_list.insert(0, input().title())
print()
print("Here is your list")
print(grocery_list)
